name: widget-server pipe DOCKERHUB

on: 
  push:
    branches:
      - 'main'

jobs: 
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: Install dependencies
        id: install-dependencies
        run: |
          pnpm install

      - name: Login to Docker Hub
        id: login-docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tag
        id: generate-tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build and push the image Test
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: |
            ${{ vars.CONTAINER_REPOSITORY }}:test-${{ steps.generate-tag.outputs.sha }}
      
      - name: Run Trivy Scanner
        id: run-trivy-scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: '${{ vars.CONTAINER_REPOSITORY }}:test-${{ steps.generate-tag.outputs.sha }}'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
      
      # - name: Build and push the image to Docker Hub
      #   id: build-push-image
      #   env: 
      #     DOCKERHUB_REPOSITORY: ${{ vars.CONTAINER_REPOSITORY }}
      #     IMAGE_TAG: ${{ steps.generate-tag.outputs.sha }}
      #   run: |
      #     docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
      #     docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG

      - name: Build and push the image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.CONTAINER_REPOSITORY }}:${{ steps.generate-tag.outputs.sha }}