name: widget-server pipe

on: 
  push:
    branches:
      - 'main'
env: 
  CONTAINER_REPOSITORY: 'rafaellodi/widget-server'

jobs: 
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build and push the image to AWS ECR
        id: build-push-image
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} 
          ECR_REPOSITORY: ${{ vars.CONTAINER_REPOSITORY }}
        run: |
          docker build -t widget-server:v1 .
          docker tag widget-server:v1 $ECR_REPOSITORY/$ECR_REPOSITORY:v3
          docker push $ECR_REPOSITORY/$ECR_REPOSITORY:v3